version: '3.8'
services:
  social-frontend:
    image: registry.digitalocean.com/magnus-images/social:frontend-0.4.2
    container_name: social-frontend
    networks:
      - social-app
    restart: unless-stopped

networks:
  social-app:
    name: social-app
    driver: bridge
